apiVersion: v1
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: git-backend-workspace
spec:
  params:
  - name: url
    value: https://github.com/rhtconsulting/tssc-docs.git
  - name: revision
    value: master
  type: git
