apiVersion: v1
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: git-backend-workspace
spec:
  params:
  - name: url
    value: http://gitea.apps.tssc.rht-set.com/tssc-references/tssc-reference-app-quarkus-rest-json.git
  - name: revision
    value: master
  type: git
