apiVersion: apps/v1
kind: Deployment
metadata:
  name: quarkus
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: quarkus
  template:
    metadata:
      labels:
        app: quarkus
    spec:
      containers:
      - image: quay.io/hgerlach/quarkus-quickstart:v0.1
        name: quarkus
        ports:
        - containerPort: 8080
