kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: quarkus
  namespace: default
  labels:
    app.kubernetes.io/instance: quarkus
spec:
  to:
    kind: Service
    name: quarkus-quickstart-blue
    weight: 50
  alternateBackends:
  - kind: Service
    name: quarkus-quickstart-green
    weight: 50
  wildcardPolicy: None
